#!/bin/bash

# Save current directory
dir=$PWD

# Check if dotfiles is present in $HOME

if [ -d $HOME/dotfiles ]; then
    echo "Correct dotfiles location, starting installing process"
else
    echo "Dotfiles should be present in home directory! Please change it before trying to install again"
    exit 1
fi

# Check if zsh is default shell
if [ $SHELL != "/usr/bin/zsh" ]; then
    echo "Zsh should be your default shell. Set it before using install process!"
    exit 1
fi

# Check if oh-my-zsh is installed
if [ -d ~/.oh-my-zsh ]; then
	echo "oh-my-zsh is already installed, skipping"
else
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo "Copying theme file"
    cp $HOME/dotfiles/zsh-theme/* $HOME/.oh-my-zsh/themes
fi


# Check if we need to change directory to copy files
dir_change=false
if [ $dir != $HOME/dotfiles ]; then
    echo "Changing dir to the correct one"
    cd $HOME/dotfiles
    dir_change=true
fi

# Array with files to ignore during transfer
ignore_files=("README.md" "install" "zsh-theme")

# Transfer normal files
for FILE in *; do
    # Check if file is not on ignore list
    if printf '%s\n' "${ignore_files[@]}" | grep -Fxq $FILE; then
        :
    else
        # Check if file is not already present in the correct location
        if [ ! -f $HOME/.$FILE ] && [ ! -d $HOME/.$FILE ]; then
            # Create symbolic link for file
            ln -s $HOME/dotfiles/$FILE $HOME/.$FILE
        fi
    fi
done
echo "Copied files to home dir"

# Check if dir changed for normal file transfer
if [ "$dir_change" = true ]; then
    echo "Falling back to the original dir"
    cd $dir
fi